# Generated by Django 5.1.11 on 2025-09-20 10:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Venue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True)),
                ('venue_type', models.CharField(blank=True, help_text='e.g., Football ground, Indoor court', max_length=64)),
                ('capacity', models.PositiveIntegerField(blank=True, null=True)),
                ('location_note', models.CharField(blank=True, max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='VenuePhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='venues/')),
                ('caption', models.CharField(blank=True, max_length=120)),
                ('venue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='facilities.venue')),
            ],
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.DateTimeField()),
                ('end', models.DateTimeField()),
                ('purpose', models.CharField(blank=True, max_length=120)),
                ('tournament_match_id', models.PositiveIntegerField(blank=True, db_index=True, null=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='facility_bookings', to=settings.AUTH_USER_MODEL)),
                ('venue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='facilities.venue')),
            ],
            options={
                'ordering': ['start'],
                'constraints': [models.UniqueConstraint(fields=('venue', 'start', 'end'), name='unique_exact_slot_per_venue'), models.CheckConstraint(condition=models.Q(('end__gt', models.F('start'))), name='booking_valid_range')],
            },
        ),
    ]
