# Generated by Django 5.1.11 on 2025-09-30 20:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('facilities', '0002_booking_decided_at_booking_decided_by_booking_status_and_more'),
    ]

    operations = [
    ]
