# Generated by Django 5.1.11 on 2025-09-30 20:59

import django.core.validators
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0001_initial'),
        ('tournaments', '0002_constraints_indexes'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lineupentry',
            options={'ordering': ['is_bench', 'position__code', 'user__first_name', 'id']},
        ),
        migrations.AlterModelOptions(
            name='match',
            options={'ordering': ['tournament_id', 'round_no', 'scheduled_at', 'id']},
        ),
        migrations.AlterUniqueTogether(
            name='lineup',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='lineupentry',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='tournament',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='match',
            name='round_no',
            field=models.PositiveSmallIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='tournamentteam',
            name='seed',
            field=models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AddConstraint(
            model_name='lineup',
            constraint=models.UniqueConstraint(fields=('match', 'team'), name='uniq_lineup_per_match_team'),
        ),
        migrations.AddConstraint(
            model_name='lineupentry',
            constraint=models.UniqueConstraint(fields=('lineup', 'user'), name='uniq_user_per_lineup'),
        ),
    ]
