# Generated by Django 5.1.11 on 2025-08-19 21:22

import admissions.models
import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ApplicationCycle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['-start_date'],
                'indexes': [models.Index(fields=['is_active', 'start_date'], name='admissions__is_acti_8956f4_idx')],
            },
        ),
        migrations.CreateModel(
            name='SportsQuotaApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sport', models.CharField(db_index=True, max_length=80)),
                ('playing_position', models.CharField(blank=True, max_length=80)),
                ('level', models.CharField(choices=[('college', 'College'), ('district', 'District'), ('state', 'State'), ('national', 'National'), ('international', 'International')], db_index=True, max_length=20)),
                ('years_experience', models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(40)])),
                ('previous_institution', models.CharField(blank=True, max_length=200)),
                ('academic_summary', models.TextField(blank=True, help_text='Marks/grades summary or notes.')),
                ('achievements', models.TextField(blank=True, help_text='Major tournaments, medals, ranks.')),
                ('status', models.CharField(choices=[('submitted', 'Submitted'), ('under_review', 'Under Review'), ('approved', 'Approved'), ('rejected', 'Rejected')], db_index=True, default='submitted', max_length=20)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('review_notes', models.TextField(blank=True)),
                ('locked', models.BooleanField(default=False)),
                ('applicant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='applications', to=settings.AUTH_USER_MODEL)),
                ('cycle', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='applications', to='admissions.applicationcycle')),
                ('reviewer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_sports_applications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-submitted_at'],
            },
        ),
        migrations.CreateModel(
            name='ApplicationDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doc_type', models.CharField(choices=[('participation', 'Participation Certificate'), ('merit', 'Merit/Medal Certificate'), ('id_proof', 'ID Proof'), ('photo', 'Passport Size Photo'), ('medical', 'Medical Fitness Certificate'), ('other', 'Other')], max_length=20)),
                ('file', models.FileField(help_text='PDF/JPG/PNG only. Max 5 MB.', upload_to='admissions/%Y/%m/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'jpg', 'jpeg', 'png']), admissions.models.validate_file_size])),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='admissions.sportsquotaapplication')),
            ],
            options={
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.AddIndex(
            model_name='sportsquotaapplication',
            index=models.Index(fields=['status', 'sport'], name='admissions__status_19e67e_idx'),
        ),
        migrations.AddIndex(
            model_name='sportsquotaapplication',
            index=models.Index(fields=['cycle', 'status'], name='admissions__cycle_i_323989_idx'),
        ),
        migrations.AddConstraint(
            model_name='sportsquotaapplication',
            constraint=models.UniqueConstraint(fields=('applicant', 'cycle', 'sport'), name='unique_applicant_cycle_sport', violation_error_message='You already applied for this sport in the current cycle.'),
        ),
        migrations.AddIndex(
            model_name='applicationdocument',
            index=models.Index(fields=['doc_type', 'uploaded_at'], name='admissions__doc_typ_c684ee_idx'),
        ),
    ]
