# Generated by Django 5.1.11 on 2025-09-16 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admissions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sportsquotaapplication',
            name='sport',
            field=models.CharField(choices=[('football', 'Football'), ('basketball', 'Basketball'), ('volleyball', 'Volleyball'), ('badminton', 'Badminton'), ('cricket', 'Cricket'), ('athletics', 'Athletics')], db_index=True, max_length=20),
        ),
    ]
