# Generated by Django 5.1.11 on 2025-08-19 21:30

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', accounts.models.UserManager()),
            ],
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('coach', 'Coach'), ('staff', 'Staff'), ('student', 'Student'), ('guest', 'Guest')], db_index=True, default='guest', max_length=20),
        ),
    ]
