# Generated by Django 5.1.11 on 2025-08-22 07:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_user_managers_alter_user_role'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PlayerProfile',
        ),
    ]
