# Generated by Django 5.1.11 on 2025-08-13 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(db_index=True, max_length=255)),
                ('sport', models.CharField(db_index=True, max_length=100)),
                ('bio', models.TextField(blank=True)),
                ('achievements', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['full_name'],
                'indexes': [models.Index(fields=['full_name'], name='players_pla_full_na_c03349_idx'), models.Index(fields=['sport'], name='players_pla_sport_1e85ea_idx')],
            },
        ),
    ]
