# Generated by Django 5.1.11 on 2025-09-21 03:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='formation',
            name='counts_by_code',
        ),
        migrations.CreateModel(
            name='FormationPosition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.PositiveSmallIntegerField(default=0)),
                ('formation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='positions', to='players.formation')),
                ('position', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='formation_rows', to='players.position')),
            ],
            options={
                'ordering': ['id'],
                'constraints': [models.UniqueConstraint(fields=('formation', 'position'), name='unique_position_per_formation')],
            },
        ),
    ]
